version: "3"
services:
  edgedb:
    restart: always
    image: edgedb/edgedb
    ports:
      - "5656:5656"
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode

  bot:
    restart: always
    build: .
    depends_on:
      - edgedb

    env_file:
      - .env
